apiVersion: v1
kind: Pod
metadata:
  name: agent-k8s-example
  namespace: cicd
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      tty: true
